version: '3.8'

services:

  chat-server:
    build: ../chat-server
    container_name: chat-server
    restart: always
    env_file:
      - ../chat-server/.env
    volumes:
      - ../chat-server:/app
    ports:
      - 8020:8000

  mcp-server:
    build: ../mcp-server
    container_name: mcp-server
    restart: always
    env_file:
      - ../mcp-server/.env
    volumes:
      - ../mcp-server:/app
    ports:
      - 8019:8000

  dozzle:
    container_name: log-viewer
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080

networks:
  default:
    driver: bridge
